### ISSUE TITLE
Incorrect html structure generated by the plugin

### ISSUE THREAD

**Issue by bramley** [michield/phplist-plugin-attributeselect#3]
The plugin is generating structurally incorrect html in method sendMessageTab().

The element `<div class="accordion">` on line 59 is not closed. It used to be closed but a recent push request has removed the closing tag on line 129.

There is an extra closing table tag on line 127.

**Comment by michield** [comment]
serves me right for not double checking pull requests ... I think it's ok now, but reopen if not
